"""
gallery.py — build a dark, responsive HTML gallery of the generated slides.
Works with either PNG (real model) or SVG (stub) slide files.
"""

import html
import os
import webbrowser


def build_gallery(slides: list, brand_data: dict, out_dir: str,
                  open_browser: bool = False) -> str:
    brand_name = html.escape(brand_data.get("brand_name", "Brand"))
    cards = []
    for s in slides:
        if not s.get("ok"):
            cards.append(
                f'<div class="card err"><div class="pill">{html.escape(s["type"].upper())}</div>'
                f'<p>generation failed</p></div>'
            )
            continue
        swatch = s.get("bg_color_1", "#888")
        cards.append(f'''<div class="card">
      <img src="{html.escape(s["file"])}" alt="slide {s['slide']}"/>
      <div class="meta">
        <span class="pill">{html.escape(s["type"].upper())}</span>
        <span class="dot" style="background:{html.escape(swatch)}"></span>
      </div>
      <h3>{html.escape(s.get("headline",""))}</h3>
      <p>{html.escape(s.get("subtext",""))}</p>
    </div>''')

    doc = f'''<!doctype html><html lang="en"><head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>{brand_name} — Carousel</title>
<style>
  body {{ background:#0a0a0a; color:#f5f5f5; font-family:-apple-system,Segoe UI,Roboto,sans-serif; margin:0; padding:48px; }}
  h1 {{ font-size:44px; margin:0 0 8px; }}
  .sub {{ color:#888; margin:0 0 40px; }}
  .grid {{ display:grid; grid-template-columns:repeat(3,1fr); gap:28px; }}
  @media (max-width:900px) {{ .grid {{ grid-template-columns:repeat(2,1fr); }} }}
  @media (max-width:600px) {{ .grid {{ grid-template-columns:1fr; }} }}
  .card {{ background:#161616; border-radius:16px; overflow:hidden; box-shadow:0 8px 30px rgba(0,0,0,.45); padding-bottom:16px; }}
  .card img {{ width:100%; display:block; }}
  .meta {{ display:flex; align-items:center; gap:10px; padding:14px 16px 0; }}
  .pill {{ background:#2a2a2a; color:#ddd; font-size:12px; font-weight:700; letter-spacing:.08em; padding:5px 12px; border-radius:999px; }}
  .dot {{ width:16px; height:16px; border-radius:50%; border:2px solid #333; }}
  .card h3 {{ margin:12px 16px 4px; font-size:18px; }}
  .card p {{ margin:0 16px; color:#999; font-size:14px; }}
  .err {{ display:flex; flex-direction:column; gap:10px; align-items:center; justify-content:center; min-height:200px; color:#a55; }}
  footer {{ margin-top:48px; color:#555; font-size:13px; }}
</style></head><body>
  <h1>{brand_name}</h1>
  <p class="sub">Branded Instagram carousel — {len([s for s in slides if s.get("ok")])} slides</p>
  <div class="grid">
    {''.join(cards)}
  </div>
  <footer>Generated by the Foundry · Claude Code · provider-agnostic image pipeline</footer>
</body></html>'''

    path = os.path.join(out_dir, "index.html")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(doc)
    if open_browser:
        try:
            webbrowser.open(f"file://{path}")
        except Exception:
            pass
    return path
